### ISSUE TITLE
While loading plugin `melte-compiler` from package `zodern:melte`:    packages/zodern:melte-compiler/options.js:15:15: Cannot read property 'runtimePackage' of undefined

### ISSUE THREAD

**Issue by jaybeemind** [zodern/melte-compiler#1]
Hi, I'm having this problem after updating to Meteor 2.2:   

```
While loading plugin `melte-compiler` from package `zodern:melte`:
   packages/zodern:melte-compiler/options.js:15:15: Cannot read property 'runtimePackage' of undefined
   at module (packages/zodern:melte-compiler/options.js:15:15)
   at fileEvaluate (packages/modules-runtime.js:336:7)
   at Module.require (packages/modules-runtime.js:238:14)
   at Module.moduleLink
   (C:\Users\Administrator\AppData\Local\.meteor\packages\zodern_melte\1.4.2\plugin.melte-compiler.os\npm\node_modules\meteor\modules\node_modules\reify\lib\runtime\index.js:52:22)
   at module (packages/melte-compiler/plugin.js:1:131)
   at fileEvaluate (packages/modules-runtime.js:336:7)
   at Module.require (packages/modules-runtime.js:238:14)
   at require (packages/modules-runtime.js:258:21)
   at <runJavaScript-37>:42:1
   at <runJavaScript-37>:47:3
```

**Comment by zodern** [comment]
It is fixed in zodern:melte-compiler@1.0.1
