### ISSUE TITLE
PostCSS preprocessing breaks with Svelte versions 3.30.0+

### ISSUE THREAD

**Issue by arggh** [zodern/melte-compiler#3]
If I try to define PostCSS plugins when using Svelte version `3.30.0` or later, the build crashes on few different errors, depending on the Svelte version. This error is one of them:

```
/Users/arggh/.meteor/packages/coffeescript/.1.0.17.jzhn4e.2mhnq++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^

TypeError: processed.code.replace is not a function
    at parse_attached_sourcemap (/Users/arggh/Develop/app/node_modules/svelte/src/compiler/utils/mapped_code.ts:305:34)
    at processed_tag_to_code (/Users/arggh/Develop/app/node_modules/svelte/src/compiler/preprocess/index.ts:111:2)
    at process_single_tag (/Users/arggh/Develop/app/node_modules/svelte/src/compiler/preprocess/index.ts:168:10)
```

Reproduction: https://github.com/arggh/meteor-melte-version-issue/

**Comment by arggh** [comment]
Currently `melte-compiler` uses the full return value from postcss as value of `code` in style preprocessor return value. That used to work, for some reason, before Svelte `3.30.0`, but not anymore.

eg.

```js
{
  code: { css: '.example { ... }', postcssStuff, fileInfo etc. }
}
```

Pull request #4 fixes this by using only the raw css value as value of `code`.

eg.

```js
{
  code: '.example { ... }'
}
```
